name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress comand line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste
        run: ${{github.event.inputs.cli}}

      
