name: Cypress cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comand line
        default: cypress/e2e/*

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2] 
        
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{github.event.inputs.spec}}
          #parallel: true
          
        env:
          CYPRESS_RECORD_KEY: 4ebd3b2b-8714-47d9-9e49-00a8f58bc456
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
          
          
